[package]
name = "fs_mod_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
md5 = "0.7.0"
regex = "1.11.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
zip = "2.2.0"
